version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mlflow
    hostname: mlflow
    volumes:
      - ./01-intro:/app/01-intro
      - ./02-experiment-tracking:/app/02-experiment-tracking
    environment:
      - MLFLOW_ARTIFACT_ROOT=/app/02-experiment-tracking/mlflow_artifacts
    ports:
      - "8000:8000"
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mlops

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    networks:
      - mlops

networks:
  mlops:
    name: MLOPS
    driver: bridge