services:
  python_app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: python_app
    hostname: python_app
    volumes:
      - ./01-intro:/app/01-intro
    ports:
      - "8000:8000"
