FROM python:3.9-slim

# Set Python-related environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install -U pip && pip install pipenv
RUN pip install pipenv
WORKDIR /app
COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy

COPY [ "predict.py", "lin_rdge.bin", "./" ]

EXPOSE 9696
CMD ["python", "-m", "uvicorn", "predict:app", "--host=0.0.0.0", "--port=9696"]
